version: '3'

networks:
  net:

volumes:
  client-volume:
    name: client-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/client/src

  server-volume:
    name: server-volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./requirements/server/src

secrets:
  environment:
    file: ./.env

services:
  client:
    container_name: client
    image: client-img
    build:
      context: ./client
    restart: always
    volumes:
      - client-volume:/client
    networks:
      - net
    secrets:
      - environment
    environment:
      SERVER_ADDR: server
      SERVER_PORT: "${SERVER_PORT}"
    depends_on:
      - server

  server:
    container_name: server
    image: server-img
    build:
      context: ./server
    restart: always
    volumes:
      - server-volume:/server
    networks:
      - net
    secrets:
      - environment
    environment:
      SERVER_ADDR: "${SERVER_ADDR}"
      SERVER_PORT: "${SERVER_PORT}"
    expose:
      - "${SERVER_PORT}"